version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      # ports from container exposed to the docker machine and the guest machine
    ports:
      - "9999:9999"
